import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ContactRound, Loader2, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

export default function ContactsPage() {
  const tenants = trpc.tenant.mine.useQuery();
  const [tenantId, setTenantId] = useState<number | null>(null);
  const [search, setSearch] = useState("");
  const [creating, setCreating] = useState(false);
  useEffect(() => { if (!tenantId && tenants.data?.[0]) setTenantId(tenants.data[0].id); }, [tenantId, tenants.data]);
  const contacts = trpc.contacts.list.useQuery({ tenantId: tenantId ?? 0 }, { enabled: !!tenantId });
  const filtered = useMemo(() => (contacts.data ?? []).filter(contact => `${contact.name} ${contact.phone} ${contact.company ?? ""}`.toLowerCase().includes(search.toLowerCase())), [contacts.data, search]);
  if (tenants.isLoading || !tenantId) return <div className="grid min-h-[55vh] place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#5d8b75]" /></div>;
  return <div className="mx-auto max-w-6xl space-y-6 p-2 sm:p-5"><section className="flex flex-col justify-between gap-4 rounded-[1.7rem] border border-[#dfe9e2] bg-[#f3f8f4] p-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#5d8f78]">Relacionamento por tenant</p><h1 className="mt-2 font-display text-4xl tracking-[-.035em] text-[#213c47]">Contatos</h1><p className="mt-2 text-sm text-[#687980]">Dados de clientes isolados por empresa e vinculados às conversas do atendimento.</p></div><Button onClick={() => setCreating(value => !value)} className="rounded-full bg-[#203b47] text-white hover:bg-[#2d4f5b]"><Plus className="mr-2 h-4 w-4" />Novo contato</Button></section>{creating && <ContactForm tenantId={tenantId} onDone={() => { setCreating(false); contacts.refetch(); }} />}<section className="rounded-3xl border border-[#dfe8e2] bg-white p-5"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-[#87959a]" /><Input value={search} onChange={event => setSearch(event.target.value)} className="pl-9" placeholder="Buscar por nome, telefone ou empresa" /></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{contacts.isLoading ? <Loader2 className="m-6 h-5 w-5 animate-spin" /> : filtered.length ? filtered.map(contact => <ContactCard key={contact.id} tenantId={tenantId} contact={contact} onChanged={() => contacts.refetch()} />) : <p className="py-10 text-center text-sm text-[#7d8b91]">Nenhum contato neste tenant.</p>}</div></section></div>;
}

function ContactForm({ tenantId, onDone }: { tenantId: number; onDone: () => void }) {
  const create = trpc.contacts.create.useMutation({ onSuccess: () => { toast.success("Contato criado."); onDone(); }, onError: error => toast.error(error.message) });
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [company, setCompany] = useState(""); const [notes, setNotes] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ tenantId, name, phone, email, company, notes }); };
  return <form onSubmit={submit} className="grid gap-4 rounded-3xl border border-[#dfe8e2] bg-white p-6 md:grid-cols-2"><div className="space-y-1.5"><Label>Nome</Label><Input value={name} onChange={event => setName(event.target.value)} required /></div><div className="space-y-1.5"><Label>Telefone</Label><Input value={phone} onChange={event => setPhone(event.target.value)} required /></div><div className="space-y-1.5"><Label>E-mail</Label><Input type="email" value={email} onChange={event => setEmail(event.target.value)} /></div><div className="space-y-1.5"><Label>Empresa</Label><Input value={company} onChange={event => setCompany(event.target.value)} /></div><div className="space-y-1.5 md:col-span-2"><Label>Notas</Label><Textarea value={notes} onChange={event => setNotes(event.target.value)} /></div><div className="md:col-span-2"><Button type="submit" disabled={create.isPending} className="rounded-full bg-[#203b47] text-white hover:bg-[#2d4f5b]">{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Salvar contato</Button></div></form>;
}

function ContactCard({ tenantId, contact, onChanged }: { tenantId: number; contact: { id: number; name: string; phone: string; email: string | null; company: string | null; notes: string | null }; onChanged: () => void }) { const [editing, setEditing] = useState(false); const update = trpc.contacts.update.useMutation({ onSuccess: () => { toast.success("Contato atualizado."); setEditing(false); onChanged(); }, onError: error => toast.error(error.message) }); const remove = trpc.contacts.delete.useMutation({ onSuccess: () => { toast.success("Contato removido."); onChanged(); }, onError: error => toast.error(error.message) }); const [name, setName] = useState(contact.name); const [phone, setPhone] = useState(contact.phone); const [email, setEmail] = useState(contact.email || ""); const [company, setCompany] = useState(contact.company || ""); const [notes, setNotes] = useState(contact.notes || ""); return <article className="rounded-2xl border border-[#e1e9e4] bg-[#fbfcfb] p-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf5e9]"><ContactRound className="h-4 w-4 text-[#648f76]" /></div><div className="min-w-0 flex-1"><p className="truncate font-bold text-[#405760]">{contact.name}</p><p className="mt-0.5 text-xs text-[#78878d]">{contact.phone}</p></div><Button size="icon" variant="ghost" onClick={() => setEditing(value => !value)}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" disabled={remove.isPending} onClick={() => { if (window.confirm(`Remover ${contact.name}?`)) remove.mutate({ tenantId, contactId: contact.id }); }}><Trash2 className="h-4 w-4 text-[#b06a59]" /></Button></div>{contact.company && <p className="mt-3 text-xs font-semibold text-[#6e817c]">{contact.company}</p>}{contact.email && <p className="mt-1 truncate text-xs text-[#87959a]">{contact.email}</p>}{editing && <form onSubmit={event => { event.preventDefault(); update.mutate({ tenantId, contactId: contact.id, name, phone, email, company, notes }); }} className="mt-4 grid gap-2"><Input value={name} onChange={event => setName(event.target.value)} required /><Input value={phone} onChange={event => setPhone(event.target.value)} required /><Input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="E-mail" /><Input value={company} onChange={event => setCompany(event.target.value)} placeholder="Empresa" /><Textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Notas" /><Button type="submit" disabled={update.isPending} className="w-fit rounded-full bg-[#203b47] text-white hover:bg-[#2d4f5b]">{update.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Salvar</Button></form>}</article>; }
