import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Building2, Loader2, LockKeyhole, ShieldCheck } from "lucide-react";
import { useEffect } from "react";
import { Link, useLocation } from "wouter";

export default function CustomerLogin() {
  const { loading, user } = useAuth(); const [, setLocation] = useLocation();
  const tenants = trpc.tenant.mine.useQuery(undefined, { enabled: Boolean(user) });
  useEffect(() => { if (user && tenants.data) setLocation(tenants.data.length ? "/app" : "/onboarding"); }, [user, tenants.data, setLocation]);
  if (loading || (user && tenants.isLoading)) return <div className="grid min-h-screen place-items-center bg-[#f8f7f4]"><Loader2 className="h-6 w-6 animate-spin text-[#5d8b75]" /></div>;
  if (user && tenants.isError) return <div className="grid min-h-screen place-items-center bg-[#f8f7f4] p-5"><section className="max-w-md rounded-3xl border border-[#eadbd5] bg-white p-8 text-center"><h1 className="font-display text-3xl text-[#273f49]">Não foi possível abrir sua operação.</h1><p className="mt-3 text-sm leading-6 text-[#738189]">Tente novamente para localizar a empresa vinculada à sua conta.</p><Button onClick={() => tenants.refetch()} className="mt-6 rounded-full bg-[#1c3542] text-white">Tentar novamente</Button></section></div>;
  if (user) return <div className="grid min-h-screen place-items-center bg-[#f8f7f4]"><Loader2 className="h-6 w-6 animate-spin text-[#5d8b75]" /></div>;
  return <div className="min-h-screen bg-[#f8f7f4] px-5 py-10 sm:py-16"><div className="mx-auto grid max-w-5xl overflow-hidden rounded-[2rem] border border-[#dbe6df] bg-white shadow-[0_22px_70px_rgba(30,54,62,.11)] lg:grid-cols-[.86fr_1.14fr]"><aside className="bg-[#193540] p-8 text-white sm:p-12"><Link href="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#c8f27c] font-display text-lg italic text-[#203d39]">L</div><span className="font-display text-xl">lyra</span></Link><p className="mt-14 text-xs font-bold uppercase tracking-[.18em] text-[#c3ef82]">Acesso do cliente</p><h1 className="mt-4 font-display text-4xl leading-tight">Sua operação, com contexto e controle.</h1><p className="mt-5 max-w-sm text-sm leading-6 text-[#bbcad0]">Entre para abrir apenas a empresa vinculada à sua conta. Conversas, integrações e documentos permanecem isolados por tenant.</p><div className="mt-12 space-y-4 text-sm text-[#dce7e8]"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-[#b9ec7d]" />Autenticação protegida</div><div className="flex gap-3"><Building2 className="h-5 w-5 shrink-0 text-[#b9ec7d]" />Acesso direcionado à sua empresa</div></div></aside><section className="flex flex-col justify-center p-8 sm:p-12"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#edf6e8]"><LockKeyhole className="h-5 w-5 text-[#548269]" /></div><h2 className="mt-5 font-display text-3xl text-[#213c47]">Entrar no Lyra</h2><p className="mt-3 max-w-md text-sm leading-6 text-[#728189]">Use sua conta de acesso para continuar. Após a autenticação, você será direcionado automaticamente para o painel da sua empresa.</p><Button size="lg" onClick={() => startLogin("/login")} className="mt-8 h-12 rounded-full bg-[#1c3542] text-white hover:bg-[#294956]">Continuar para o login seguro <ArrowRight className="ml-2 h-4 w-4" /></Button><Link href="/" className="mt-5 text-center text-sm font-semibold text-[#5d8b75] hover:text-[#274d45]">Voltar para a página inicial</Link></section></div></div>;
}
