import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Building2, Loader2, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

export default function PlatformPage() {
  const tenants = trpc.platform.tenants.useQuery();
  const changeStatus = trpc.platform.setTenantStatus.useMutation({ onSuccess: () => { tenants.refetch(); toast.success("Status do tenant atualizado."); }, onError: error => toast.error(error.message) });
  if (tenants.isLoading) return <div className="grid min-h-[55vh] place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#5d8b75]" /></div>;
  return <div className="mx-auto max-w-6xl space-y-6 p-2 sm:p-5"><section className="flex flex-col justify-between gap-4 rounded-[1.7rem] border border-[#dce7df] bg-[#193540] p-7 text-white sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#c6ee86]">Super-admin da plataforma</p><h1 className="mt-2 font-display text-4xl tracking-[-.035em]">Governança de tenants</h1><p className="mt-2 text-sm text-[#bfd0d4]">Ações administrativas globais, isoladas da operação de cada cliente.</p></div><ShieldCheck className="h-8 w-8 text-[#c6ee86]" /></section><section className="overflow-hidden rounded-3xl border border-[#dfe8e2] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead><tr className="border-b border-[#e8eeea] text-xs uppercase tracking-[.12em] text-[#87959a]"><th className="p-4">Empresa</th><th className="p-4">Plano</th><th className="p-4">Assinatura</th><th className="p-4">Status</th><th className="p-4">Ação</th></tr></thead><tbody>{tenants.data?.map(tenant => <tr key={tenant.id} className="border-b border-[#eef2ef] last:border-0"><td className="p-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf5e9]"><Building2 className="h-4 w-4 text-[#5d8d73]" /></div><div><p className="font-bold text-[#425861]">{tenant.name}</p><p className="text-xs text-[#7d8b91]">{tenant.primaryEmail}</p></div></div></td><td className="p-4 text-sm text-[#65777f]">{tenant.planName || "—"}</td><td className="p-4 text-sm text-[#65777f]">{tenant.subscriptionStatus || "—"}</td><td className="p-4"><Badge className={tenant.status === "suspended" ? "bg-[#fff0eb] text-[#a66049]" : "bg-[#e8f5e5] text-[#4c805a]"}>{tenant.status}</Badge></td><td className="p-4"><Button size="sm" variant="outline" onClick={() => changeStatus.mutate({ tenantId: tenant.id, status: tenant.status === "suspended" ? "active" : "suspended" })} className="rounded-full">{tenant.status === "suspended" ? "Reativar" : "Suspender"}</Button></td></tr>)}</tbody></table></div></section></div>;
}
